# Внутри ето файла саписываються инструкции для запуска сразу несколько контейнеров сразу для docker-compose 

# version указывает версию нашего docker-compose
version: '3.8'

# services описывают работу всех docker контейнеров
services:
  # указываем название сервиса , можна вибирать любое название
  postgres-db:
    # указываем образ, который будет основой нашего текущего(одного) сервиса
    image: postgres:latest
    # даем название для текущего контейнера(сервиса) для удобного показывания в консоли
    container_name: postgres
    # environment внутри храняться переменные, которые нужны для нормальной работы текущего сервиса
    # переменные берутся из описания основного образа для нашего сервиса
    environment:
      # ник пользователя подключеного к базе 
      POSTGRES_USER: postgres
      # пароль для входа в базу для текущего пользтователя
      POSTGRES_PASSWORD: 1856
      # название для нашой уже существующей базы данных
      POSTGRES_DB: my_test
    ports:
      # указываем связь по порту между нашим проектом и базой данных внутри контейнера(сервиса)
      # порт нашего локальной проекта  :  порт внутри контейнера
      - "5432:5432"
  
  # второй сервис нашего проекта
  django:
    # берем образ для сервиса из нашего Docker File проекта
    build:
      # указываем путь где лежит Docker File
      context: ./my_app
    ports:
      - "8001:8000"
    # указываем какие сервисы должны быть запущены для начала работы текущего
    # 
    depends_on: 
      - postgres-db
    # указываем вирутальные окружения внутри нашего текущего сервиса
    environment:
      DEBUG: "False"
      DB_NAME: "my_test"
      DB_USER: "postgres"
      DB_PASSWORD: "1856"
      # для хоста указываем название контейнера (из container_name) внутри которого лежит PostgreSQL
      DB_HOST: "postgres"
      DB_PORT: "5432"






















