# Внутри ето файла саписываються инструкции для запуска сразу несколько контейнеров сразу 

# version указываем версию нашего проекта
version: '3.8'

# services описывают работу всех docker контейнеров
services:
  # указываем название сервиса , можна вибирать любое название
  # в текущем запускаем базу данных 
  postgres-db:
    # указываем образ, который будет основой нашего текущего(одного) сервиса
    image: postgres:latest
    # environment внутри храняться переменные, которые нужны для нормальной работы текущего сервиса
    # переменные берутьвся из описания основного образа для нашего сервиса
    environment:
      POSTGRES_USER: kondrich
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_test_db
    ports:
      # указываем связь по порту локальной базы и базы в сервисе
      # первое значение - локальная базы : второе значение база в нашем сервисе
      - "5432:5432"